### PR TITLE
The NewWeek-clone Project completed.

### PR DESCRIPTION
**Pull request by M-Alamgir**
The Newsweek-clone Project built with HTML5, CSS3, and Bootstrap.

### CODE REVIEW

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @ourandco  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your clone looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you used Sementic HTML
:+1: Your readme looks great (just one or two things to fix) but it really good I like it, keep it up :muscle: 
:+1: I see that you have put in a lot of energy to make this project, that is also a great thing worth appreciation, we are very proud of you here at [Microverse](https://microverse.org/) :gift:
:+1: I liked that you took advantage of the power of SASS, keep it up :muscle: 
#### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
### General
- [x] Fix the lincense link from the readme file, it's not working
- [x] In the acknowledgement section, you are acknowledging [The Next web](https://thenextweb.com/) :point_right: is this right or it should be [newsweek](https://www.newsweek.com/)
- [x] Add the project's description in your readme file, describe your project, it makes your repo look very professional.
- [x] Fix the issues link from the readme file, it's not working

### UI/UX
- [x] At the end of `Opinions` section (right most of the page) you should have added the form which has an email input field and signup button 


| Your clone | Original page |
| --- | --- |
| :grey_question: :grey_question: :grey_question:  | Screenshot from 2020-12-09 20-54-29|

- [x] Add some spacing between social network icons at the rightmost of the footer
- [x] The login link should change into user icon on mobile screens 


| Your clone | Original page |
| --- | --- |
| Screenshot from 2020-12-09 23-06-31| Screenshot from 2020-12-09 20-47-27 |

:point_right: Could you see the difference :question: :question: :question: 

- [x] email input field which is at the top of the signup button of the newsletter section is not designed as the one on the source page
- [x] In mobile screen, the top story section should be the first on at the top, currently on your clone, the featured stories are at the top, please fix that
- [x] The picture which is on the leftmost side of the subscribe section, should be two overlapping pictures


| Your clone | Original page |
| --- | --- |
|Screenshot from 2020-12-09 23-04-19| Screenshot from 2020-12-09 23-05-14|

:point_right: Could you see the difference :question: :question: :question: 

- [x] The newsletter section should be one column on mobile screens means that picture should occupy the whole width of the screen and the form as well. 


| Your clone | Original page |
| --- | --- |
|Screenshot from 2020-12-09 23-02-33|Screenshot from 2020-12-09 23-03-11|

:point_right: Could you see the difference :question: :question: :question: 

- [x] You have only three social icons on the footer, whereas the original page contains five socila icons, please add them all
- [x] The newsweek logo in footer should be red, use the relevant logo there.
- [x] Fix the footer to make it look like the original on bot medium and small screens

| Your clone | Original page |
| --- | --- |
|Screenshot from 2020-12-09 23-00-33|Screenshot from 2020-12-09 23-01-10|

:point_right: Could you see the difference :question: :question: :question: 

- [x] Generally your page is distorted on smaller screens (320 px)

| Your clone | Original page |
| --- | --- |
|Screenshot from 2020-12-09 22-58-13| Screenshot from 2020-12-09 20-57-50|

:point_right: Could you see the difference :question: :question: :question: 



### Codes
- [x] You have used `display: flex;` in your CSS file, since this project focuses on bootstrap, please use utility classes of bootstrap to cover that

# [Optional changes] :yellow_circle: 
- [x] If you have some other social network links, it will be nice if you put them on the readme file
- [x] Try to implement the polygon at the right most of the red navbar

:warning: Your commit messages should be in imperative mode or present tense, _i.e.:_ you should have written `Complete magazine section` instead of writing `magazine section completed.`, refer [to this article for more details on how to write a good && professional commit message](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by M-Alamgir** [comment]
Thanks, Mugirase Emmanuel for your review,
I have made your suggested changes.

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @ourandco**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [x] the secondary navbar disappears in the tablet and mobile views. 

original
Capture1

clone
Capture



---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by M-Alamgir** [comment]
Thanks, Mahmoud Mohammad
Done.

**Review by layzrd — CHANGES_REQUESTED** [review]
### Status: Require changes 🌳 ♲
Hi @, I am  [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  👏👏   I appreciate your hard work in replicating newsweek.com. Kindly fix the issues stated in the previous review. 

The CULTURE & TRAVEL and MORE STORIES are not similar to the source.
The Sponsered insight and sign-up form size do not resemble the source.
The Editors Pick section should have two articles per row on medium screens.


| Your Copy | Source | 
| :---:         |     :---:      |
| Screen Shot 2020-12-10 at 5 55 34 PM   | Screen Shot 2020-12-10 at 5 13 48 PM     |
| Screen Shot 2020-12-10 at 5 54 33 PM     |   Screen Shot 2020-12-10 at 5 09 15 PM     | 
|Screen Shot 2020-12-10 at 5 55 01 PM|Screen Shot 2020-12-10 at 5 36 07 PM|



Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Comment by M-Alamgir** [comment]
Thanks, Abdulaziz Redi Ali,
I have made your suggested changes to the Editors, Opinion,  Culture & Travel sections.

**Comment by mimipeshy** [comment]
## STATUS: APPROVED 🥳 🍾 
Hello @ourandco, good job on working on all comments left by TSE's 👏 👏 , I, therefore, approve this project, go ahead and merge. All the best in the next projects

Regards
Peris Ndanu

**Pull request merged**
